###
GET http://localhost:4004/inv

###
GET http://localhost:4004/inv/Inventory?$filterby...

###
POST http://localhost:4004/orders/Order
Content-Type: application/json

{
    "item":"Coke",
    "quantity": 1
}
